# -*- coding: utf-8 -*-
"""Chapter 2: Variables & Comments

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eS_fMA3qG6BLeci_AhOO6RVTNN8UqQvl

Exercise 1: Variables☑️

Type out the code below and add the correct data types to complete the variables

Assign a message to a variable, and print that message. Then change the value of the variable to a new message, and print the new message.
"""

number = 8

print(number)

number = 9291

print(number)

"""Exercise 2: Variables ☑️

Find a quote from a famous person you admire. Print the quote and the name of its author.

Your output should look something like the following, including the quotation marks:

Albert Einstein once said, “A person who never made a mistake never tried anything new.
"""

print("Nelson Madela once said, \"The greatest glory in living lies not in never falling, but in rising every time we fall.\"")

"""Exercise 3: Stripping Names ☑️

Tidy up the code to make it easier to understand

Use a variable to represent a person’s name, and include some whitespace characters at the beginning and end of the name. Make sure you use each character combination, “\t” and “\n”, at least once.

Print the name once, so the whitespace around the name is displayed.

Then print the name using each of the three stripping functions, lstrip(), rstrip(), and strip().
"""

name = "\n\tKenryan Luke Arias\t"

print(name)

print(name.lstrip())

print(name.rstrip())

name1 = ",.,,.,.Kenryan Luke Ariaspopopopo"
print(name1)


print(name1.strip(",.po"))

"""Exercise 4: Favorite Number ☑️

Use a variable to represent your favorite number.
Then, using that variable, create a message that reveals your favorite number. Print that message.
"""

fav_number = "11"

print("My favourite number is " + fav_number)


"""Exercise 5: USB Shopper ☑️

A girl heads to a computer shop to buy some USB sticks. She loves USB sticks and wants as many as she can get for £50. They are £6 each.

Write a programme that calculates how many USB sticks she can buy and how many pounds she will have left.

You will to use the arithmetic operators to complete this exercise.
"""

usb = 6

money = 50

amount = money // usb

change = money % usb

print("Amount of USB sticks:")

print(amount)

print("Remaining change:")

print(change)


