# -*- coding: utf-8 -*-
"""CH1: Exercise 1 answer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Mly1yBXMKLMyttIKJBcierSHP9PCYNL
"""

print("Twinkle, twinkle, little star,")
print("How I wonder what you are! Up above the world so high,")
print("Like a diamond in the sky.")
print("Twinkle, twinkle, little star, How I wonder what you are")