# -*- coding: utf-8 -*-
"""Chapter 1 : Getting started with Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NN_z5z9t0NPaqNWbuB3zc2nqhuNp_xaW

Exercise 1: Print Strings ☑️

Write a Python program to print the following string in a specific format.

Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How I wonder what you are
"""

print("Twinkle, twinkle, little star,")
print("How I wonder what you are! Up above the world so high,")
print("Like a diamond in the sky.")
print("Twinkle, twinkle, little star, How I wonder what you are")

"""Exercise 2: Print the Version of Python ☑️

Write a Python program to get the Python version you are using.
"""

import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)

"""Exercise 3: Print date and Time ☑️

Write a Python program to display the current date and tim
"""

import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d %H:%M:%S"))

"""Exercise 4: Strings Concatination ☑️

Write three strings in different variables and print the output as one string.    
"""

word1 = "three"
word2 = "different"
word3 = "variables"
print(word1 ,word2 ,word3)

"""Exercise 5: Compute area of Circle ☑️

Write a Python program which accepts the radius of a circle from the user and compute the area.
"""

r = int(input("Enter radius of circle: "))
pi = 3.14159
area = pi * r **2
print(area)